FROM java:8

MAINTAINER RETURN<543851436@qq.com>

COPY target/*.jar ocBackstage.jar
ADD http://nginx.org/download/nginx-1.18.0.tar.gz /usr/local/src



EXPOSE 8081

ENTRYPOINT ["java","-jar","ocBackstage.jar","--spring.profiles.active=prod"]
