server:
  port: 8081

spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 300MB
      enabled: true

  mail:
    username: 18398858464@163.com
    password: ZTUDFDOLCYGOFZJF
    host: smtp.163.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oracleclub?serverTimezone=GMT%2b8&characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  typeAliasesPackage: com.oracleclub.server.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  global-config:
    banner: false
  type-enums-package: com.oracleclub.server.entity.enums

logging:
  level:
    com.oracleclub.server: DEBUG
  file:
    path: ${user.home}/oc/logs

system:
  setting:
    file-location: ${user.home}/oc
