server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://oc-db:3306/oracleclub?serverTimezone=GMT&characterEncoding=utf8
    username: root
    password: ph18398858464
    type: com.alibaba.druid.pool.DruidDataSource
